### ISSUE TITLE
Typo in vars

### ISSUE THREAD

**Issue by gaborho** [WillJCJ/eks-terraform-demo#1]
It's great, thank you for your work. Just wanted to leave a note that there is a typo in ${var.availablilty_zones}. It should be availability_zones instead of availab**li**lty_zones

**Comment by WillJCJ** [comment]
Thank you! I've added that fix to my latest commit (e76df5e378e54033d1c53bfedfe2bdb622a0e5e1). 

I also made it easier to apply the initial config map to allow nodes to join your EKS cluster, something I forgot to do this afternoon while making one!
